from .OCRNet_Manager import OCRNetManager
from .Vit_Manager import VitManager
from .MultiVit_Manager import MultiVitManager
from .VitMae_Manager import VitMaeManager
from .MultiVitMae_Manager import MultiVitMaeManager
from .MultiVitMaeSeq_Manager import MultiVitMaeSeqManager
from .CLIP_Manager import CLIPManager
from .CLIPTransfer_Manager import CLIPTransferManager
from .CLIPTransferSingle_Manager import CLIPTransferSingleManager
